#!/usr/bin/env python3
"""Safe intent-based AI agent for the GitOps Kubernetes portfolio.

This is intentionally conservative:
- Natural language is mapped to a small allowlist of intents.
- Intents map to fixed command templates or documentation responses.
- Commands are dry-run by default; use --execute to run them.
- No arbitrary shell generated by an LLM is executed.
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWED_INTENTS = {
    "check_status",
    "validate_repo",
    "open_argocd",
    "open_nginx_demo",
    "show_secrets_policy",
    "show_bootstrap_steps",
    "show_troubleshooting",
    "list_apps",
    "help",
}


@dataclasses.dataclass(frozen=True)
class AgentResult:
    intent: str
    explanation: str
    commands: tuple[tuple[str, ...], ...] = ()
    docs: tuple[Path, ...] = ()


class IntentError(ValueError):
    pass


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


def classify(text: str) -> str:
    q = normalize(text)

    if any(k in q for k in ["상태", "status", "헬스", "health", "확인", "문제"]):
        if any(k in q for k in ["시크릿", "secret", "비밀번호", "토큰"]):
            return "show_secrets_policy"
        return "check_status"

    if any(k in q for k in ["검증", "validate", "검사", "yaml", "kubeconform", "ci"]):
        return "validate_repo"

    if any(k in q for k in ["argocd", "argo cd", "argo"]):
        if any(k in q for k in ["열", "open", "브라우저", "접속", "ui"]):
            return "open_argocd"
        return "show_bootstrap_steps"

    if any(k in q for k in ["nginx", "whoami", "demo", "앱", "브라우저", "열어"]):
        return "open_nginx_demo"

    if any(k in q for k in ["시크릿", "secret", "토큰", "비밀번호", "api key", "apikey"]):
        return "show_secrets_policy"

    if any(k in q for k in ["부트스트랩", "bootstrap", "설치", "install", "시작"]):
        return "show_bootstrap_steps"

    if any(k in q for k in ["트러블", "trouble", "에러", "오류", "안돼", "안됨"]):
        return "show_troubleshooting"

    if any(k in q for k in ["목록", "list", "뭐가", "구성", "앱들"]):
        return "list_apps"

    return "help"


def build_llm_prompt(user_text: str) -> str:
    intents = ", ".join(sorted(ALLOWED_INTENTS - {"help"}))
    return (
        "You are a safe GitOps Kubernetes intent classifier. "
        "Return JSON only, with this exact shape: "
        '{"intent":"one_allowed_intent","arguments":{}}. '
        f"Allowed intents: {intents}. "
        "Never return shell commands, secrets, tokens, explanations, markdown, or extra keys. "
        f"User request: {user_text}"
    )


def parse_llm_intent(raw: str) -> str:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise IntentError(f"Invalid LLM JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise IntentError("Invalid LLM JSON: root must be an object")
    intent = payload.get("intent")
    if not isinstance(intent, str):
        raise IntentError("Invalid LLM JSON: intent must be a string")
    if intent not in ALLOWED_INTENTS:
        raise IntentError(f"Unsupported LLM intent: {intent}")
    return intent


def classify_with_llm(text: str) -> str:
    api_key = os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    if not api_key:
        raise IntentError("OPENAI_API_KEY is not set")
    body = json.dumps(
        {
            "model": model,
            "messages": [{"role": "user", "content": build_llm_prompt(text)}],
            "temperature": 0,
            "response_format": {"type": "json_object"},
        }
    ).encode()
    req = urllib.request.Request(
        f"{base_url}/chat/completions",
        data=body,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        data = json.loads(response.read().decode())
    content = data["choices"][0]["message"]["content"]
    return parse_llm_intent(content)


def build_result(intent: str) -> AgentResult:
    if intent == "check_status":
        return AgentResult(
            intent=intent,
            explanation="클러스터와 GitOps 리소스 상태를 확인합니다.",
            commands=(
                ("kubectl", "get", "nodes", "-o", "wide"),
                ("kubectl", "get", "applications", "-n", "argocd"),
                ("kubectl", "get", "pods", "-A"),
                ("kubectl", "get", "svc", "-A"),
            ),
        )
    if intent == "validate_repo":
        return AgentResult(
            intent=intent,
            explanation="레포의 YAML과 Python demo backend 문법을 검증합니다.",
            commands=(
                ("python3", "scripts/validate-yaml.py"),
                ("python3", "-m", "py_compile", "services/fastapi-demo/app/main.py"),
            ),
        )
    if intent == "open_argocd":
        return AgentResult(
            intent=intent,
            explanation="Argo CD UI를 localhost:8080으로 port-forward 합니다. 실행 후 https://127.0.0.1:8080 접속.",
            commands=(("kubectl", "-n", "argocd", "port-forward", "svc/argocd-server", "8080:443"),),
        )
    if intent == "open_nginx_demo":
        return AgentResult(
            intent=intent,
            explanation="demo namespace의 whoami 서비스를 localhost:8081로 port-forward 합니다. 실행 후 http://127.0.0.1:8081 접속.",
            commands=(("kubectl", "-n", "demo", "port-forward", "svc/whoami", "8081:80"),),
        )
    if intent == "show_secrets_policy":
        return AgentResult(
            intent=intent,
            explanation="Secret 관리 정책 문서를 보여줍니다. 실제 secret 값은 출력하지 않습니다.",
            docs=(REPO_ROOT / "docs/secrets.md",),
        )
    if intent == "show_bootstrap_steps":
        return AgentResult(
            intent=intent,
            explanation="Argo CD bootstrap 절차 문서를 보여줍니다.",
            docs=(REPO_ROOT / "docs/bootstrap.md",),
        )
    if intent == "show_troubleshooting":
        return AgentResult(
            intent=intent,
            explanation="트러블슈팅 문서를 보여줍니다.",
            docs=(REPO_ROOT / "docs/troubleshooting.md",),
        )
    if intent == "list_apps":
        return AgentResult(
            intent=intent,
            explanation="GitOps App of Apps에 포함된 Application 목록을 출력합니다.",
            commands=(("python3", "agent/list_apps.py"),),
        )
    if intent == "help":
        return AgentResult(
            intent=intent,
            explanation=(
                "지원 요청 예시:\n"
                "- 클러스터 상태 확인해줘\n"
                "- yaml 검사해줘\n"
                "- Argo CD UI 열어줘\n"
                "- nginx demo 브라우저로 열어줘\n"
                "- 시크릿 정책 보여줘\n"
                "- bootstrap 방법 알려줘"
            ),
        )
    raise IntentError(f"Unsupported intent: {intent}")


def print_result(result: AgentResult, execute: bool) -> int:
    print(f"Intent: {result.intent}")
    print()
    print(result.explanation)
    print()

    for doc in result.docs:
        print(f"--- {doc.relative_to(REPO_ROOT)} ---")
        if doc.exists():
            print(doc.read_text())
        else:
            print(f"missing doc: {doc}")

    if not result.commands:
        return 0

    print("Commands:")
    for cmd in result.commands:
        print("  " + " ".join(cmd))
    print()

    if not execute:
        print("Dry-run only. 실제 실행하려면 --execute 옵션을 붙이세요.")
        return 0

    for cmd in result.commands:
        print(f"$ {' '.join(cmd)}")
        proc = subprocess.run(cmd, cwd=REPO_ROOT, text=True)
        if proc.returncode != 0:
            return proc.returncode
    return 0


def ask(args: argparse.Namespace) -> int:
    if args.llm:
        try:
            intent = classify_with_llm(args.text)
        except IntentError as exc:
            print(f"LLM classification failed: {exc}", file=sys.stderr)
            print("Falling back to rule-based classifier.", file=sys.stderr)
            intent = classify(args.text)
    else:
        intent = classify(args.text)
    return print_result(build_result(intent), execute=args.execute)


def run_intent(intent: str, execute: bool) -> int:
    return print_result(build_result(intent), execute=execute)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Safe AI agent for GitOps Kubernetes portfolio")
    sub = parser.add_subparsers(dest="command", required=True)

    p_ask = sub.add_parser("ask", help="Map natural language to a safe intent")
    p_ask.add_argument("text")
    p_ask.add_argument("--execute", action="store_true")
    p_ask.add_argument("--llm", action="store_true", help="Use OpenAI-compatible API for intent classification, then validate allowlist")
    p_ask.set_defaults(func=ask)

    for name, intent in [
        ("status", "check_status"),
        ("validate", "validate_repo"),
        ("apps", "list_apps"),
        ("secrets", "show_secrets_policy"),
        ("bootstrap", "show_bootstrap_steps"),
        ("troubleshoot", "show_troubleshooting"),
    ]:
        p = sub.add_parser(name)
        p.add_argument("--execute", action="store_true")
        p.set_defaults(func=lambda args, i=intent: run_intent(i, args.execute))

    p_open = sub.add_parser("open", help="Open a known service via kubectl port-forward")
    p_open.add_argument("target", choices=["argocd", "whoami"])
    p_open.add_argument("--execute", action="store_true")
    def _open(args: argparse.Namespace) -> int:
        return run_intent("open_argocd" if args.target == "argocd" else "open_nginx_demo", args.execute)
    p_open.set_defaults(func=_open)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
